validate: True
imbalanced_learn: False
tune_hyperparameter: False

data_dir: "data"
results_dir: "results"
data_file: "creditcard.csv"
test_file: "test_values.csv"
target_name: "Class"
output_file: "predictions.csv"

steps_dir: "config/steps"
hyperparameter_tuning_config_dir: config/hyperparameter-tuning.yaml
imbalanced_learning_config_dir: config/imbalanced_learning.yaml





