algorithm_name: RandomizedSearchCV
algorithm_parameters:
  param_distributions:
    classification__n_estimators: 25-500
    classification__min_samples_split: 2-11
    classification__min_samples_leaf: 1-11
    classification__max_depth: 2-50
  n_iter: 100
  scoring: 
    - recall
    - f1
  refit: recall
  cv: 2
  verbose: 1
  n_jobs: -1



